<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="112794" started-at="2018-06-21T06:03:40Z" finished-at="2018-06-21T06:05:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="112794" started-at="2018-06-21T06:03:40Z" finished-at="2018-06-21T06:05:33Z">
      <class name="org.dbserver.evaluation.store.testcases.BuyProductTestCase">
        <test-method status="PASS" signature="start()[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="start" is-config="true" duration-ms="10755" started-at="2018-06-21T06:03:40Z" finished-at="2018-06-21T06:03:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="testOne(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="testOne" duration-ms="36861" started-at="2018-06-21T06:03:51Z" data-provider="ProductSearch" finished-at="2018-06-21T06:04:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Batman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Resultados da pesquisa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[button_cart_ajax94]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[det_img_1860791280]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="PASS" signature="testOne(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="testOne" duration-ms="27741" started-at="2018-06-21T06:04:28Z" data-provider="ProductSearch" finished-at="2018-06-21T06:04:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PS3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Resultados da pesquisa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[button_cart_ajax90]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[det_img_1770303465]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="FAIL" signature="testTwo(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="testTwo" duration-ms="18085" started-at="2018-06-21T06:04:55Z" data-provider="ProductSearch" finished-at="2018-06-21T06:05:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Batman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Resultados da pesquisa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[button_cart_ajax94]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[det_img_1860791280]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Batman]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Batman]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.dbserver.evaluation.store.testcases.BuyProductTestCase.testTwo(BuyProductTestCase.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="FAIL" signature="testTwo(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="testTwo" duration-ms="17865" started-at="2018-06-21T06:05:14Z" data-provider="ProductSearch" finished-at="2018-06-21T06:05:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PS3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Resultados da pesquisa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[button_cart_ajax90]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[det_img_1770303465]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [PS3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [PS3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.dbserver.evaluation.store.testcases.BuyProductTestCase.testTwo(BuyProductTestCase.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.dbserver.evaluation.store.testcases.BuyProductTestCase@124ac145]" name="tearDown" is-config="true" duration-ms="1435" started-at="2018-06-21T06:05:31Z" finished-at="2018-06-21T06:05:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.dbserver.evaluation.store.testcases.BuyProductTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
